OdeToFood/OdeToFood/ViewModels/HomeIndexViewModels.cs
using OdeToFood.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewModels
{
    public class HomeIndexViewModels
    {
        public IEnumerable<Restaurant> Restaurants { get; set; }
        public String CurrentMessage { get; set; }
    }
}

OdeToFood/OdeToFood/ViewModels/RestaurantEditModel.cs
using OdeToFood.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace OdeToFood.ViewModels
{
    public class RestaurantEditModel
    {
        [Required, MaxLength(80)]
        public String Name { get; set; }
        public CusineType Cusine { get; set; }
    }
}

OdeToFood/OdeToFood/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Controllers
{
    [Route("[controller]/[action]")]
    public class AboutController
    {
        
        public String Phone()
        {
            return "11 984023261";
        }

        
        public String Address()
        {
            return "Rua Paim, 90";

        }
    }
}

OdeToFood/OdeToFood/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Model;
using OdeToFood.Services;
using OdeToFood.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.wwwroot.Controllers
{
    [Authorize]
    public class HomeController: Controller
    {
        private IRestaurantData _restaurantData;
        private IGreeter _greeter;

        public HomeController(IRestaurantData restaurantData, IGreeter greeter) 
        {
            _restaurantData = restaurantData;
            _greeter = greeter;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var model = new HomeIndexViewModels();
            model.Restaurants = _restaurantData.GetAll();
            model.CurrentMessage = _greeter.GetMessageOfDay();
            return View(model);
        }

        public IActionResult Details(int id)
        {
            var model = _restaurantData.Get(id);
            if(model == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
          
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RestaurantEditModel model )
        {
            if(ModelState.IsValid)
            {
                var newRestaurante = new Restaurant();
                newRestaurante.Name = model.Name;
                newRestaurante.Cusine = model.Cusine;

                newRestaurante = _restaurantData.Add(newRestaurante);


                return RedirectToAction(nameof(Details), new { id = newRestaurante.Id });
                
            }
            else
            {
                return View();
            }
            
        }
    }
}

OdeToFood/OdeToFood/Pages/Greeting.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Services;

namespace OdeToFood.Pages
{
    public class GreetingModel : PageModel
    {
        private IGreeter _greeter;

        public string CurrentGreeting { get; set; }
        public GreetingModel(IGreeter greeter)
        {
            this._greeter = greeter;
        }
        public void OnGet(String name)
        {
            this.CurrentGreeting =  $"{name}: {this._greeter.GetMessageOfDay()}" ;

        }
    }
}

OdeToFood/OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Model;
using OdeToFood.Services;

namespace OdeToFood.Pages.Restaurants
{
    [Authorize]
    public class EditModel : PageModel
    {

        private IRestaurantData _restaurantData;

        [BindProperty]
        public Restaurant Restaurant { get; set; }
        public EditModel(IRestaurantData restaurantData)
        {
            this._restaurantData = restaurantData;
        }
        public IActionResult OnGet(int id)
        {
           this.Restaurant = _restaurantData.Get(id);
            if(this.Restaurant == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                _restaurantData.Update(this.Restaurant);
                return RedirectToAction("Details", "Home", new { id = this.Restaurant.Id });
            }
            return Page();
        }
    }
}

OdeToFood/OdeToFood/ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class GreeterViewComponent : ViewComponent
    {
        private IGreeter _gretter;

        public GreeterViewComponent(IGreeter greeter)
        {
            _gretter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _gretter.GetMessageOfDay();
            return View("Default", model);
        }
    }
}

OdeToFood/OdeToFood/ViewComponents/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class LoginLogoutViewComponent: ViewComponent
    {
        
        private IGreeter _gretter;

        public LoginLogoutViewComponent(IGreeter greeter)
        {
            _gretter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _gretter.GetMessageOfDay();
            return View("Default", model);
        }
    }
}

OdeToFood/OdeToFood/Pages/Greeting.cshtml
@page "{name}"

@model GreetingModel

<div>@Model.CurrentGreeting</div>

OdeToFood/OdeToFood/Pages/Restaurants/Edit.cshtml
@page "{id}"
@using OdeToFood.Pages.Restaurants


@model EditModel
@{
}

<h1>Edit</h1>
<form method="post">
    <input type="hidden" asp-for="Restaurant.Id" />
    <div>
        <label asp-for="Restaurant.Name"></label>
        <input asp-for="Restaurant.Name" />
        <span asp-validation-for="Restaurant.Name"></span>
    </div>
    <div>
        <label asp-for="Restaurant.Cusine"></label>
        <select asp-for="Restaurant.Cusine"
                asp-items="@Html.GetEnumSelectList<CusineType>()"></select>
        <span asp-validation-for="Restaurant.Cusine"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>

OdeToFood/OdeToFood/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer",required:false)
    </footer>
</body>
</html>

OdeToFood/OdeToFood/Views/Home/Create.cshtml
@using OdeToFood.Model
@model OdeToFood.Model.Restaurant

@{
    ViewBag.Title = "Create";

}

<h1>Create</h1>

<form method="post">
    <div>
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <label asp-for="Cusine"></label>
        <select asp-for="Cusine"
                asp-items="@Html.GetEnumSelectList<CusineType>()"></select>
        <span asp-validation-for="Cusine"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>

OdeToFood/OdeToFood/Views/Home/Details.cshtml
@model OdeToFood.Model.Restaurant
@{
    ViewBag.Title = "Details";

}


<h1>@Model.Name</h1>
<div>
    ID: @Model.Id
</div>
<div>
    Cuisine: @Model.Cusine
</div>

<a asp-action="Index" asp-controller="Home">Home</a>

OdeToFood/OdeToFood/Views/Home/Index.cshtml
@model OdeToFood.ViewModels.HomeIndexViewModels


<h1>All Restaurants</h1>

@foreach (var restaurant in Model.Restaurants)
{
    @Html.Partial("_Summary", restaurant)
}
   

<div><a class="btn btn-primary" asp-action="Create">Add Restaurant</a></div>

@section footer {
    @Model.CurrentMessage
}

OdeToFood/OdeToFood/Views/Home/_Summary.cshtml
@model Restaurant

<section class="panel panel-default">
    <h3 class="panel-heading">@Model.Name</h3>
    <div class="panel-body">
        Cusine: @Model.Cusine
    </div>
    <div class="panel-footer">
        <a class="btn btn-default" asp-action="Details" asp-route-id="@Model.Id">More</a>
        <a class="btn btn-default" asp-page="/Restaurants/Edit" asp-route-id="@Model.Id">Edit</a>
    </div>
</section>

OdeToFood/OdeToFood/Views/Shared/Components/Greeter/Default.cshtml
@model String

<div>
    @Model
</div>

OdeToFood/OdeToFood/Views/Shared/Components/LoginLogout/Default.cshtml
@if (User.Identity.IsAuthenticated)
{
    <div>Hello, @User.Identity.Name</div>
    <a class="btn btn-default" asp-controller="Account" asp-action="Logout"/>
}
else
{
    <a class="btn btn-default" asp-controller="Account" asp-action="Login">Login</a>
}

OdeToFood/OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <environment include="Development">
        <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    </environment>
    
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">OdeToFood</a>
            </div>
            <div class="navbar-right">
                <vc:login-logout></vc:login-logout>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        <footer>
            @RenderSection("footer", required: false)
            <vc:greeter></vc:greeter>

        </footer>
    </div>
    <environment include="Development">
        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
        <script src="~/node_modules/jquery-validation/dist/jquery.validate.js"></script>
    </environment>


</body>
</html>